### ISSUE TITLE
Add --config path for .semrelrc location

### ISSUE THREAD

**Issue by CandiedCode** [go-semantic-release/semantic-release#103]
For my golang project structure layout, my ci/cd related scripts/configs are located in [/build](https://github.com/golang-standards/project-layout/tree/master/build)

I do this with other tools such as 
```
golangci-lint run --config build/golangci-lint/.golangci.yml
goreleaser --config build/goreleaser/.goreleaser.yaml
```

I would like a flag option to set the config file location via --config.

**Comment by christophwitzko** [comment]
This is a great idea! 👍

**Comment by soohoowoohoo** [comment]
@christophwitzko @cliedeman I'd be interested in working on this. Is this fine with y'all?

**Comment by christophwitzko** [comment]
@soohoowoohoo Sure, feel free to open a PR. ☺️ 🙏
