### ISSUE TITLE
Plugins discovery behind proxy

### ISSUE THREAD

**Issue by avillalain** [go-semantic-release/semantic-release#107]
Hi

I'm wondering if there is a way to configure the execution to disable the plugin discoverability feature. Basically the environment where I'm running can't issue any outside calls to fetch packages, and I'm wondering as an alternative to be able to have a docker image with all plugins already packaged to be able to run it

**Comment by christophwitzko** [comment]
Hi @avillalain,

`semantic-release` is currently not working behind a proxy. There is an option to pre-download the required plugins called `--download-plugins`. You can use the following Dockerfile to build an image containing all required plugins:

```Dockerfile
FROM registry.gitlab.com/go-semantic-release/semantic-release:2.13.0

RUN semantic-release --download-plugins
``` 

I am also happy to add proxy support to semantic-release. I will have some time in the following weeks to look into that issue.

Best,
Christoph

**Comment by avillalain** [comment]
Actually this might work, but I'm running a test, and I still see that it's trying to download plugins, even though I moved all plugins to the .semrel folder where the tool is installed, is there a set of env. variables that I need to set so that semantic-release do not check for plugins and use the ones already downloaded?

**Comment by christophwitzko** [comment]
Okay, that means probably that `semantic-release` downloads the wrong plugins. Make sure to set the correct provider, ci condition, etc plugin as CLI flags, e.g.:
`semantic-release --download-plugins --provider gitlab --ci-condition gitlab`

**Comment by avillalain** [comment]
@christophwitzko even with the plugins downloaded the binary is trying to pull the list of plugins, is there a way to turn that off?

**Comment by christophwitzko** [comment]
Hmm, `semantic-release` only contacts the registry if the plugin was not found locally. 🤔 What plugins are you using for your setup? Can you post your semantic-release log output?

**Comment by christophwitzko** [comment]
Okay, thanks for sharing. The `--prepend-changelog` does not require a separate plugin. The download plugins command looks correct. Currently, semantic-release requires having the `.semrel` directory in the current working directory and I am not sure if soft-linking is enough. Can you try to copy the `.semrel` folder where you are executing `semantic-release`?

**Comment by avillalain** [comment]
@christophwitzko copying the folder worked perfectly. I thought of the needing the `.semrel` in the working directory, but did not think that I needed to copy it directly. Thanks again, I'll see if this approach can work, I'm hoping to see if I can download the plugins first and that might be an alternative.

**Comment by avillalain** [comment]
@christophwitzko I'm exploring a workaround using the proxy to download those binaries from github. And I'm downloading them but I'm not sure why `go-semantic-release` is trying to hit the plugin list.  Basically I'm manually creating the `.semrel` folder structure, with the following plugins: 

- changelog-generator-default
- commit-analyzer-default
- condition-default
- files-updater-npm
- provider-git

An `ls` into the folder `.semrel/linux_amd64` looks like the following: 
```
drwxr-xr-x 3 root root 4096 Mar 16 16:17 changelog-generator-default
drwxr-xr-x 3 root root 4096 Mar 16 16:21 commit-analyzer-default
drwxr-xr-x 3 root root 4096 Mar 16 16:22 condition-default
drwxr-xr-x 3 root root 4096 Mar 16 16:23 files-updater-npm
drwxr-xr-x 3 root root 4096 Mar 16 16:23 provider-git
```

Internally each folder has it's corresponding folder with the latest version available in the releases. Using a the proxy artifactory repository that mirrors github, I can download the releases in those folders so basically they contain the following files
- for `changelog-generator-default`: `1.5.0/
