### ISSUE TITLE
How to release patches for older version

### ISSUE THREAD

**Issue by deveshk0** [go-semantic-release/semantic-release#108]
I have a branch setup like release-1 and release-2 which releases version like 1.x.x and for release-2 -- 2.x.x. How i can release a patch from release release-1 branch, default branch is switched to release-2

**Comment by christophwitzko** [comment]
Hi @deveshk0, this can be solved by committing a `.semrelrc` file in your branch with the content:
```json
{
  "maintainedVersion": "1"
}
```
This will tell semantic-release to stay in the 1.x.x version range and you can release patches and features for the older v1 release.

**Comment by deveshk0** [comment]
Thanks, Working fine for me.
