### ISSUE TITLE
get-release.xyz appears to be down

### ISSUE THREAD

**Issue by harrisonmuskat** [go-semantic-release/semantic-release#109]
I have noticed `get-release.xyz` seems to be having some issues today. Earlier it appeared the certificate may have expired (but then the problem was resolved) and now when I curl I get the following:

```
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to get-release.xyz:443 
```

Not 100% sure what the issue is here but figured it was worth at least noting with an issue.

**Comment by AeroNotix** [comment]
Ref: https://github.com/christophwitzko/get-release.xyz/issues/4

**Comment by christophwitzko** [comment]
My apologies, there was an issue with the new deployment setup. It is now up and running again. (see https://github.com/christophwitzko/get-release.xyz/issues/4#issuecomment-886991752)
