### ISSUE TITLE
Providing files-updater-helm plugin

### ISSUE THREAD

**Issue by SISheogorath** [go-semantic-release/semantic-release#124]
I wrote a plugin for go-semantic-release to update helm versions (https://git.shivering-isles.com/sheogorath/files-updater-helm).

While I can obviously maintain it in my own repository, I would like to push this upstream into the go-semantic-release organisation and maintain it in here. I wonder what's your opinion on that.

Note: I'm not the greatest go writer in the world, so general feedback is appreciated.

**Comment by christophwitzko** [comment]
Hi @SISheogorath, this is amazing. 🎉 Thank you ☺️ 
I will create a repository for you and once the release/build process works, I will add it to the plugin registry.
I also checked out your code and it looks very good. Just found one little thing at https://git.shivering-isles.com/sheogorath/files-updater-helm/-/blob/main/pkg/updater/helm.go#L36 Why is there no error handling?

Cheers, Chris

**Comment by SISheogorath** [comment]
Thanks! I added the content to the repository, updated the required fields and fixed the missing error handling!

Looking forward to work on this :)

**Comment by christophwitzko** [comment]
Awesome, I also added the plugin to the plugin registry. 👍  Thanks for contributing a new plugin 🎉
