### ISSUE TITLE
How to release from maintenance branches?

### ISSUE THREAD

**Issue by holtakj** [go-semantic-release/semantic-release#125]
Hi,

How to release from a maintenance branch?

My situation:
Last tagged(released) version: v0.4.1
And I want to release a fix for 0.3.x which should be 0.3.17 as 0.3.16 is the last 0.3.x released version.

I`ve tried to release from branches 0.3.x and 0.3.0 and some other variants but the version (I did a dry run) was always 0.4.2.

Thank you.

**Comment by christophwitzko** [comment]
Hi @holtakj, did you check in a `.semrelrc` file on your maintenance branch?
```json
{
  "maintainedVersion": "0.3"
}
```
This tells semantic-release to stay in the `0.3.x` range.

**Comment by holtakj** [comment]
Thanks. that worked fine. Maybe make it clear in the documentation.
