### ISSUE TITLE
GITHUB_TOKEN environemnt variable not detected

### ISSUE THREAD

**Issue by talolard** [go-semantic-release/semantic-release#13]
Hi, I'm trying to run SR but it won't detect my github token in the environment variable. 
```bash
tal@FlufenSystem:~$ echo $GITHUB_TOKEN 
mytokendfpo4iwretglksdjfoisduisgd
tal@FlufenSystem:~$ semantic-release 
[semantic-release]: github token missing
tal@FlufenSystem:~$ 

```
Running Ubuntu 16, installed SR with

`      - curl -SL https://get-release.xyz/semantic-release/linux/amd64 -o ~/semantic-release && chmod +x ~/semantic-release
`

Thanks

**Comment by christophwitzko** [comment]
Hi, is `GITHUB_TOKEN` also exported? (with `export GITHUB_TOKEN`)

**Comment by talolard** [comment]
Nope. Just defined in .profile. 
That fixes it. Thanks
