### ISSUE TITLE
How to automatically generate CHANGELOG and push it back to repository?

### ISSUE THREAD

**Issue by mirusky** [go-semantic-release/semantic-release#131]
Self explanation question 

/label question

**Comment by christophwitzko** [comment]
Hi @mirusky, this heavily depends on the CI and git platform you use. If you are using GitHub and GitHub Actions you can use a plugin like: https://github.com/ad-m/github-push-action

**Comment by mirusky** [comment]
I wasn't sure if I needed to push it back, but as I see it necessary.

Anyway a great job.
