### ISSUE TITLE
Exit Code 0 even if Hooks plugin failed

### ISSUE THREAD

**Issue by AndreasSko** [go-semantic-release/semantic-release#138]
While developing a custom Hooks plugin I noticed that semantic-release will exit successfully, even if the Hooks plugin returned an error. I'm wondering if this is expected behavior or a bug. I think 
https://github.com/go-semantic-release/semantic-release/blob/18e8bae821ffac4f4569bc642ae3cb29ecf983f6/cmd/semantic-release/main.go#L308-L321 
is missing an `exitIfError`, which is the case for other plugin calls (like Init). 

I'm happy to open a PR if this is something that is ok to be changed :slightly_smiling_face:

**Comment by christophwitzko** [comment]
Hi @AndreasSko, the idea was that hooks plugins should never interrupt the release flow.
But I can see cases where this makes sense. We can put it behind a cli flag, so users have to explicitly enable it.

**Comment by AndreasSko** [comment]
Thank you, @christophwitzko! Really appreciate it :slightly_smiling_face:
