### ISSUE TITLE
Tag as a release candidate? 

### ISSUE THREAD

**Issue by talolard** [go-semantic-release/semantic-release#14]
Hi,
Is their a way to get semrel to tag the release as a release candidate e.g. 1.3.4-rc1 ? 
And to get this via commit message (e.g. if I specify fix(xxx):.... RC) it will tag as such ?
Thanks

**Comment by christophwitzko** [comment]
Hi Tal, that is possible but not that straightforward/easy as I wish it should be.
You have to branch out and check in a `.semrelrc` file:
https://github.com/go-semantic-release/semantic-release#beta-release-support

**Comment by ksegun** [comment]
@christophwitzko can maintainedVesion be something like 1.1.0?
