### ISSUE TITLE
Using BREAKING CHANGE

### ISSUE THREAD

**Issue by Rossiar** [go-semantic-release/semantic-release#15]
Hi - just wanted some guidance on using `BREAKING CHANGE` as specified in the original project docs: https://github.com/semantic-release/semantic-release/blob/master/README.md

There doesn't seem to be support for this as currently [this line](https://github.com/go-semantic-release/semantic-release/blob/master/semrel.go#L94) will fail to match a commit message like `BREAKING CHANGE: merry christmas guys`:
```
func parseCommit(commit *github.RepositoryCommit) *Commit {
	c := new(Commit)
	c.SHA = commit.GetSHA()
	c.Raw = strings.Split(commit.Commit.GetMessage(), "\n")
	found := commitPattern.FindAllStringSubmatch(c.Raw[0], -1)
	if len(found) < 1 {
		return c
	}
	c.Type = strings.ToLower(found[0][1])
	c.Scope = found[0][2]
	c.Message = found[0][3]
	c.Change = Change{
		Major: breakingPattern.MatchString(commit.Commit.GetMessage()),
		Minor: c.Type == "feat",
		Patch: c.Type == "fix",
	}
	return c
}
```
In the code above `commitPattern` is relying on word characters (`\w`) to match before the `:` and so it will not match against `BREAKING CHANGE` as ` ` is not a word character, as such the `found` array will be empty and the `parseCommit` function will exit early and not assign a `Change` to the commit.

I was mainly wondering if this was intentional or not and if you would accept a PR from our fork to resolve this if it is indeed a bug?

**Comment by christophwitzko** [comment]
Hi @Rossiar,

if you want to introduce a new breaking change with a commit, you still need to stick to the [Angular Commit Message Conventions](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit). That means that the `BREAKING CHANGE` keyword is part of the commit body or footer.

This is how a breaking change commit message should look like:
```
feat: this new feature changes the API behavior

BREAKING CHANGE: merry christmas
```

**Comment by Rossiar** [comment]
Hi @christophwitzko,

Thanks for clearing up my misunderstanding!
