### ISSUE TITLE
I need to find a way to create custom version numbers

### ISSUE THREAD

**Issue by viraj2252** [go-semantic-release/semantic-release#157]
I managed to successfully create a workflow and create tags and release. However, since my repo is mono repo with multiple projects, i want to create custom tag prefixes for each project.

**Comment by christophwitzko** [comment]
Hi @viraj2252, thanks for trying-out `go-semantic-release` ☺️ 

Currently, we don't support monorepos and we are not planning to in the near future (see #77).

Best,
Chris
