### ISSUE TITLE
server error trying to download semantic-release

### ISSUE THREAD

**Issue by dougdonohoe** [go-semantic-release/semantic-release#167]
This morning, we were seeing `server error` trying to curl `semantic-release`.  I'm not familiar with what/who owns `get-release.xyz`, but figured you ought to know. 
```
$ curl -SL https://get-release.xyz/semantic-release/linux/amd64 -o ./semantic-release
$ cat semantic-release
server error
```

**NOTE**: It seems to have just resolved itself (the downtime was maybe 15 minutes).

**Comment by christophwitzko** [comment]
Thanks for reporting! (and sorry for my late reply) ☺️ 

`get-release.xyz` is a small project I created a while ago: https://github.com/christophwitzko/get-release.xyz

As it is a non-commercial project I cannot provide any uptime guarantee for `get-release.xyz` 😞  But you can always use the download link directly from the GitHub releases page directly.
