### ISSUE TITLE
Question: Making it clear to goreleaser whether there are breaking changes

### ISSUE THREAD

**Issue by jamietanna** [go-semantic-release/semantic-release#171]
Related to https://github.com/goreleaser/goreleaser/discussions/4548, I'm trying to get go-semantic-release to work with goreleaser to indicate when breaking changes have been introduced in the release.

As well as this being available through the release notes, I'd also like to indicate this through [goreleaser's announcements](https://goreleaser.com/customization/announce/slack/) whether there's a breaking change in the release.

Right now, it doesn't seem possible to do this via the config in either tools.

One option for doing this would be to add an environment variable that's passed along to `goreleaser`, that then my Goreleaser config could look for the presence of.

**Comment by christophwitzko** [comment]
Fixed in https://github.com/go-semantic-release/hooks-goreleaser/releases/tag/v1.9.0

**Comment by jamietanna** [comment]
Thank you 🚀
