### ISSUE TITLE
README links to dubious website

### ISSUE THREAD

**Issue by alfa-alex** [go-semantic-release/semantic-release#176]
The main README of this project contains a link to a dubious website in this part (bold font where the link appears):
> This way no human is directly involved in the release process and your releases are guaranteed to be **unromantic and unsentimental**.

This should be corrected.

**Comment by cliedeman** [comment]
For reference: https://web.archive.org/web/20230326114353/http://sentimentalversioning.org/

I have created #177 to remove it

**Comment by christophwitzko** [comment]
Thanks @alfa-alex for reporting this 🙏  It is now removed from the README.md
