### ISSUE TITLE
Deploy to demo, production?

### ISSUE THREAD

**Issue by hazcod** [go-semantic-release/semantic-release#22]
Hi,

So I have a workflow where if I push to master (production) or demo (tda), a new release is created and docker images are pushed using this tag. I extract the version out of `.version`.

However whenever I want to deploy to production and this is already deployed on demo, the release will already exist and semantic-release will exit without `.version` file.

Your thoughts on how to handle this?

**Comment by christophwitzko** [comment]
The best way to do this would be to query the [GitHub release API](https://developer.github.com/v3/repos/releases/) and check for the latest release.
If you need help with that, I am happy to provide you with the necessary script.
Cheers,
Christoph

**Comment by hazcod** [comment]
I'm currently grepping the found version out of the `semantic-release` output in a very nasty way:
```
        wget -q -nv -O semantic-release https://get-release.xyz/semantic-release/linux/amd64 && chmod 500 semantic-release
        output="$(./semantic-release -slug venclave/master -vf -noci -token $$GITHUB_TOKEN 2>&1 || true)"
        if [ ! -f .version ]; then
          extractedVersion="$(echo "$output" | grep 'found version:' | cut -d ' ' -f 4)"
          if [ -z "$extractedVersion" ]; then
            echo -e "No version found:\n$output"
            exit 1
          fi
          echo "$extractedVersion" > .version
        fi
        echo "New version will be: $(cat .version)"
```

**Comment by christophwitzko** [comment]
Hey @hazcod, sorry for the late reply. You could do something like:
```
extractedVersion=$(curl -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/$TRAVIS_REPO_SLUG/releases/latest | jq -r '.tag_name')
```

I did not test that script, but I think it should work. Hope that helps.

Cheers,
Christoph
