### ISSUE TITLE
How to apply to all branch ? 

### ISSUE THREAD

**Issue by ArchiFleKs** [go-semantic-release/semantic-release#23]
I'm trying to have other branches make release..

```
 This test run was triggered on the branch release-1.X, while semantic-release is configured to only publish from master.
```

You can check the build here: https://travis-ci.com/clusterfrak-dynamics/teks/builds/116574231

What i'm trying to is :
- continue developing on master and release a BREAK commit to bump to v2.
- have a `release-1.X` branch which still release on v1.X

Kevin

**Comment by christophwitzko** [comment]
Hi @ArchiFleKs, thanks for using semantic-release!
For that, I created the `.semrelrc` config file. You need to check out the `release-1.X` and commit the file with the following content:
```
{
  "maintainedVersion": "1"
}
```

This will tell semantic-release to stick to 1.x.x releases on the `release-1.X` branch.

Cherrs,
Christoph

**Comment by ArchiFleKs** [comment]
Thanks for your answer it is working :) 

Now I'm trying to do a breaking release : https://github.com/clusterfrak-dynamics/teks/commit/cd89357b9e9fa2f21955f544bb725f84ef6c3408

But i still get a feature release:

https://travis-ci.com/clusterfrak-dynamics/teks/builds/117297391

Do you support the `BREAKING CHANGES:`

**Comment by christophwitzko** [comment]
Awesome!
Yes, it supports breaking changes, but the breaking change notation must be part of the commit message body.
Take a look at this commit message: https://github.com/greenkeeperio/greenkeeper-lockfile/commit/701d5cd
In your case it could look like:
```
feat: update terraform

BREAKING CHANGE: update to terraform 0.12
```
