### ISSUE TITLE
add native support for other git remote repository types

### ISSUE THREAD

**Issue by joppa27** [go-semantic-release/semantic-release#28]
semantic-release has great native support for github. It would be nice to have native support for:

- [bitbucket cloud](https://bitbucket.org)
- ~[bitbucket server](https://hub.docker.com/r/atlassian/bitbucket-server/)~ Atlassian is pulling the plug on [server licences](https://www.theregister.com/2020/10/19/atlassian_server_licenses/)
- ~[gitlab](https://gitlab.com/explore)~

**Comment by daswars** [comment]
please gitlab :)

**Comment by cliedeman** [comment]
Gitlab work started here https://github.com/go-semantic-release/semantic-release/pull/40

**Comment by christophwitzko** [comment]
GitLab support has been added in [v1.19.0](https://github.com/go-semantic-release/semantic-release/releases/tag/v1.19.0). Feel free to try it out. Thanks again to @cliedeman for the great work :)

**Comment by mirusky** [comment]
Waiting for Bitbucket Cloud

**Comment by SaturdayNightFevre** [comment]
Ive recently started using bitbucket and would be happy to contribute

**Comment by joppa27** [comment]
I'm closing this issue since 2/3 have been completed. Bitbucket support if someone wants it, should be in a separate issue imo.
