### ISSUE TITLE
Modularize semantic-release

### ISSUE THREAD

**Issue by christophwitzko** [go-semantic-release/semantic-release#4]
Split up `semantic-release` into small modules to make it more contributor friendly.

**Comment by gr2m** [comment]
Hey @christophwitzko do you want to move this to your personal account? I don’t know any go myself and can’t help much maintaining it

We can also leave it in the organization but then we should make clear that this repository is not maintained by the other maintainers (I’ll onboard a few more people of the next weeks)

**Comment by christophwitzko** [comment]
Hey @gr2m, first of all, thank you for maintaining of the JavaScript version of semantic-release. I really appreciate the time and effort you put into this project. 😊
As semantic-release is not only a solution for the JavaScript ecosystem, it makes sense to have different implementations in different programming languages in this organization. I think this is also a great popularity boost for this convenient release automation concept.
Have a nice day,
Christoph

**Comment by gr2m** [comment]
yeah I agree, are you up for maintaining the go repository in case there are any folks asking for help?

**Comment by christophwitzko** [comment]
Yes, of course.
