### ISSUE TITLE
Proposal: Plugin Interface

### ISSUE THREAD

**Issue by cliedeman** [go-semantic-release/semantic-release#48]
There are 2 options I see here.

Option 1:
Create a public entrypoint to execute semantic-release and allow users to pass in a list of plugins

Option 2:
Use the go plugin module and create a plugin interface

Example Plugin hooks and use cases:

PostReleaseCreated:
 - Post message to slack
 - create Release in jira

ProcessChangelog:
 - swap jira tickets with links. E.g. AAA-1 -> [AAA-1](http://some-link.com/AAA-1)

**Comment by christophwitzko** [comment]
This is a great idea, I have already thought about this some time ago, how to make `go-semantic-release` more extendable. I will look into that next week 👍

**Comment by cliedeman** [comment]
Reference for a plugin system I have seen that works well
- https://github.com/99designs/gqlgen/blob/master/plugin/plugin.go#L11
- https://github.com/99designs/gqlgen/blob/5e3cef245a1e87b64c8e57630fa78dae706d069b/api/generate.go#L63
