### ISSUE TITLE
Idea: Maintenance Releases

### ISSUE THREAD

**Issue by cliedeman** [go-semantic-release/semantic-release#49]
This is quite a tricky feature so nothing might ever come of this issue.

https://semantic-release.gitbook.io/semantic-release/usage/workflow-configuration

Hypothetical Scenario:

- create release 1.0.0 from master branch
- branch release-1.0.x is created.  (whenever a new minor is created a matching release branch is created)
- dev continues on master branch and 1.0.0 enters QA
- bugfix/patch needs to be created for 1.0.0
- fixes merged onto branch release-1.0.x
- release triggered on branch release-1.0.x 
- version 1.0.1 created

Requirements
- only fixes (patch level) can be merged into a release branch. Anything else will result in an error
- when a release branch get a patch this will force a minor on the next master release
- If there is a patch release done on master trying to do a patch on the release branch will eror
- This is opt in behaviour

**Comment by christophwitzko** [comment]
I think this is in a limited form already possible with the `.semrelrc` config file. Create a release branch (`release/1.x.x`) and check in the `.semrelrc` to:
```
{
  "maintainedVersion": "1.x.x"
}
```
This will allow publishing new versions from the `release/1.x.x` branch.

**Comment by cliedeman** [comment]
I think this could work if every release (Release in this case could be a sprint or a few sprints aka milestone) would be new major. 

Then there would only a few features needed to make this an automated flow
- When a new major is released automatically bump and commit maintainedVersion. (I think this could be a new command. semantic-release --new-major or something)
- Forbid major releases on maintainedVersion
- When a new major is released create a new branch called release/A.x.x where is A is the previous major

**Comment by cliedeman** [comment]
think is covered by https://github.com/go-semantic-release/semantic-release/issues/49#issuecomment-619529919
