### ISSUE TITLE
GitHub Action docs

### ISSUE THREAD

**Issue by christophwitzko** [go-semantic-release/semantic-release#50]

**Comment by hazcod** [comment]
Would very much like a GitHub action!

**Comment by hazcod** [comment]
@christophwitzko FYI am using it this way [tag.yml](https://github.com/hazcod/intigriti-slack-announce/blob/master/.github/workflows/tag.yml).
And this triggers `goreleaser` to attach artifacts [here](https://github.com/hazcod/intigriti-slack-announce/blob/master/.github/workflows/release.yml).

**Comment by idirouhab** [comment]
also, the return code is affecting the build status.
If there's nothing to change the script will exit with code 65, which is working fine with Travis but it makes GitHub action to fail.

**Comment by cliedeman** [comment]
@idirouhab created https://github.com/go-semantic-release/semantic-release/pull/66/ to fix this

**Comment by cliedeman** [comment]
Created PR for docs https://github.com/go-semantic-release/action/pull/6
