### ISSUE TITLE
Feature request: create chore commit for semantic release

### ISSUE THREAD

**Issue by Azuka** [go-semantic-release/semantic-release#74]
When running semantic-release to update the version file with `-vf`, the current commit is used to create the semantic release tag, _then_ the version file is updated, but without being pushed up to GitHub.

It would be nice to follow the behavior of the js version of semantic release, which creates a commit, then tags that commit. This would allow any CI processes to be version-aware based on the `.version` file. See https://github.com/semantic-release/semantic-release#release-steps

This can also work if the `--dry` flag updates the version file instead of erroring out as mentioned in #29 and #70

**Comment by christophwitzko** [comment]
Hi @Azuka, if you use the `--dry` flag and the `--version-file` flag it will create a `.version-unreleased` file. This will contain the expected version of the next release.
Currently, we try to decuple version changes from the commit history, so there is no plan of a chore commit for semantic-release.
