### ISSUE TITLE
semantic-release V2 has incompatible structure for import through go.mod

### ISSUE THREAD

**Issue by SergiiShapoval** [go-semantic-release/semantic-release#82]
the current repo can be used in golang projects with import through go.mod (see https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module)

but if we import the V2 version we receive the next error from go:

> go: errors parsing go.mod:
> /home/sergii/IdeaProjects/some_project/go.mod:7: require github.com/go-semantic-release/semantic-release: version "v2.6.0" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2

It can be fixed following 
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

will be great to be able to use this repo in golang projects without installing binaries

**Comment by christophwitzko** [comment]
To import v2 you would need to import `github.com/go-semantic-release/semantic-release/v2` (like here: https://github.com/go-semantic-release/provider-github/blob/master/pkg/provider/github.go#L12)

**Comment by SergiiShapoval** [comment]
hm, yep mistyped, thank you for help
