### ISSUE TITLE
Feat: Force bump patch version, if no changes are found

### ISSUE THREAD

**Issue by timoknapp** [go-semantic-release/semantic-release#98]
Hi @christophwitzko ,

while being pretty happy with the current feature-set of your `semantic-release` implementation, I notice a missing feature which would be pretty helpful for our release process. Is it already possible that you can "force bump" the patch version of a release if there are **no changes found** in the commit history? I totally know that it then might not comply with the standards of `semantic versioning`, but it can sometime happen that you need to push a hotfix and therefore did not actually use a `conventional commit` compliant commit message. It happened already twice to us, which then forced me to perform some manual tasks again, which of course is not great either.

I furthermore found a similar feature in a more legacy-ish implementation than yours. In [here](https://juhani.gitlab.io/go-semrel-gitlab/cli/v0.21.1/next-version/) the config flag is called:
> --bump-patch, -p     Bump patch number if no changes are found in log

Would be great if you agree to put something similar into your implementation. I would be also fine creating a PR for this.

Cheers
Timo

**Comment by christophwitzko** [comment]
I am happy to add that 👍  Thanks for the PR ☺️
